FROM eclipse-temurin:21-jre-jammy

RUN mkdir /deployments /ldifs \
 && chown 1001:root /deployments /ldifs \
 && chmod g+rwX /deployments /ldifs

RUN echo "securerandom.source=file:/dev/urandom" >> \
    $JAVA_HOME/conf/security/java.security

COPY target/*-runner.jar /deployments/app.jar

ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0"

EXPOSE 8080

USER 1001

ENTRYPOINT ["java","-jar","/deployments/app.jar"]
